name: CI
on:
  pull_request: {}
  push:
    branches: [main]
jobs:
  main:
    name: Build, Validate and Deploy
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: w3c/spec-prod@v2
        with:
          SOURCE: index.bs
          DESTINATION: index.html
          TOOLCHAIN: bikeshed
          GH_PAGES_BRANCH: gh-pages
      - uses: w3c/spec-prod@v2
        with:
          SOURCE: test/index.bs
          DESTINATION: test/index.html
          TOOLCHAIN: bikeshed
          GH_PAGES_BRANCH: gh-pages
